// ─── SOUND LIBRARY (48 phonemes) ─────────────────────────────────────────
// Mirrors ELSA Speak's Sound Library structure

export const SOUNDS = [
  // ════════════════════════════════════════════════════════════
  // VOWELS — Single Vowels (Monophthongs) · 14 sounds
  // ════════════════════════════════════════════════════════════
  { id:'EE',  label:'EE',  ipa:'iː', type:'vowel', group:'Single Vowels',
    color:'bg-red-700',     grad:'from-red-700 to-red-900',       hard:false,
    tip:'Kéo hai góc môi sang ngang, lưỡi cao và căng về phía trước miệng',
    words:[
      {word:'bee',   meaning:'con ong',     emoji:'🐝'},
      {word:'tree',  meaning:'cây',         emoji:'🌳'},
      {word:'feet',  meaning:'bàn chân',    emoji:'🦶'},
      {word:'sleep', meaning:'ngủ',         emoji:'😴'},
    ]},
  { id:'IH',  label:'IH',  ipa:'ɪ',  type:'vowel', group:'Single Vowels',
    color:'bg-pink-600',    grad:'from-pink-600 to-pink-800',      hard:false,
    tip:'Âm /i/ ngắn — lưỡi cao nhưng miệng thư giãn hơn EE, KHÔNG kéo căng môi',
    words:[
      {word:'fish',  meaning:'cá',          emoji:'🐟'},
      {word:'sit',   meaning:'ngồi',        emoji:'🪑'},
      {word:'bit',   meaning:'miếng nhỏ',   emoji:'🧩'},
      {word:'quick', meaning:'nhanh',       emoji:'⚡'},
    ]},
  { id:'EH',  label:'EH',  ipa:'ɛ',  type:'vowel', group:'Single Vowels',
    color:'bg-purple-700',  grad:'from-purple-700 to-purple-900',  hard:false,
    tip:'Âm "e" ngắn — miệng hé vừa, lưỡi giữa. Khác EE: không kéo môi',
    words:[
      {word:'red',    meaning:'màu đỏ',     emoji:'🔴'},
      {word:'bed',    meaning:'cái giường', emoji:'🛏️'},
      {word:'egg',    meaning:'quả trứng',  emoji:'🥚'},
      {word:'friend', meaning:'bạn bè',     emoji:'🤝'},
    ]},
  { id:'AA',  label:'AA',  ipa:'æ',  type:'vowel', group:'Single Vowels',
    color:'bg-indigo-700',  grad:'from-indigo-700 to-indigo-900',  hard:true,
    tip:'Mở miệng RỘNG hơn EH, kéo về phía trước — "ê-a" kết hợp nhanh. Khó với người Việt!',
    words:[
      {word:'cat',  meaning:'con mèo',  emoji:'🐱'},
      {word:'bag',  meaning:'cái túi',  emoji:'👜'},
      {word:'hand', meaning:'bàn tay',  emoji:'✋'},
      {word:'black',meaning:'màu đen',  emoji:'⬛'},
    ]},
  { id:'UH',  label:'UH',  ipa:'ʌ',  type:'vowel', group:'Single Vowels',
    color:'bg-teal-600',    grad:'from-teal-600 to-teal-800',      hard:true,
    tip:'Giống "ă" tiếng Việt — miệng mở vừa, lưỡi giữa-thấp. KHÔNG phải "ơ" hay "a"',
    words:[
      {word:'cup',  meaning:'cái tách', emoji:'☕'},
      {word:'bus',  meaning:'xe buýt',  emoji:'🚌'},
      {word:'duck', meaning:'con vịt',  emoji:'🦆'},
      {word:'run',  meaning:'chạy',     emoji:'🏃'},
    ]},
  { id:'uh',  label:'uh',  ipa:'ə',  type:'vowel', group:'Single Vowels',
    color:'bg-blue-700',    grad:'from-blue-700 to-blue-900',      hard:false,
    tip:'Schwa — âm trung hòa nhất, miệng HOÀN TOÀN thư giãn. Âm phổ biến nhất trong tiếng Anh!',
    words:[
      {word:'about',  meaning:'về',         emoji:'💭'},
      {word:'today',  meaning:'hôm nay',    emoji:'📅'},
      {word:'problem',meaning:'vấn đề',     emoji:'🤔'},
      {word:'banana', meaning:'chuối',      emoji:'🍌'},
    ]},
  { id:'ER',  label:'ER',  ipa:'ɜː', type:'vowel', group:'Single Vowels',
    color:'bg-fuchsia-600', grad:'from-fuchsia-600 to-fuchsia-800',hard:true,
    tip:'Môi tròn nhẹ, lưỡi giữa không chạm đâu, cuộn ra sau (giọng Mỹ). Khác "ơ" Việt: cuộn lưỡi!',
    words:[
      {word:'bird', meaning:'con chim',  emoji:'🐦'},
      {word:'word', meaning:'từ',        emoji:'📝'},
      {word:'learn',meaning:'học',       emoji:'📚'},
      {word:'turn', meaning:'quay lại',  emoji:'🔄'},
    ]},
  { id:'OO',  label:'OO',  ipa:'uː', type:'vowel', group:'Single Vowels',
    color:'bg-cyan-600',    grad:'from-cyan-600 to-cyan-800',      hard:false,
    tip:'Âm "u" dài — môi tròn căng, đẩy ra phía trước. Kéo dài hơn âm "u" tiếng Việt',
    words:[
      {word:'food',  meaning:'thức ăn',     emoji:'🍜'},
      {word:'moon',  meaning:'mặt trăng',   emoji:'🌙'},
      {word:'school',meaning:'trường học',  emoji:'🏫'},
      {word:'blue',  meaning:'màu xanh dương',emoji:'🔵'},
    ]},
  { id:'U',   label:'U',   ipa:'ʊ',  type:'vowel', group:'Single Vowels',
    color:'bg-green-700',   grad:'from-green-700 to-green-900',    hard:true,
    tip:'Âm "u" NGẮN — môi tròn nhẹ, KHÔNG căng. Khác OO: ngắn hơn và tối hơn',
    words:[
      {word:'book', meaning:'cuốn sách',emoji:'📖'},
      {word:'good', meaning:'tốt',      emoji:'👍'},
      {word:'look', meaning:'nhìn',     emoji:'👀'},
      {word:'put',  meaning:'đặt',      emoji:'👇'},
    ]},
  { id:'AW',  label:'AW',  ipa:'ɔː', type:'vowel', group:'Single Vowels',
    color:'bg-amber-600',   grad:'from-amber-600 to-amber-800',    hard:false,
    tip:'Môi tròn vừa, miệng mở. Giống "o" trong "Ông" nhưng dài hơn',
    words:[
      {word:'call',  meaning:'gọi',     emoji:'📞'},
      {word:'ball',  meaning:'quả bóng',emoji:'⚽'},
      {word:'water', meaning:'nước',    emoji:'💧'},
      {word:'small', meaning:'nhỏ',     emoji:'🔹'},
    ]},
  { id:'AH',  label:'AH',  ipa:'ɑː', type:'vowel', group:'Single Vowels',
    color:'bg-orange-600',  grad:'from-orange-600 to-orange-800',  hard:false,
    tip:'Mở miệng RỘNG nhất, lưỡi thấp phía sau. Giống "a" trong "cha"',
    words:[
      {word:'hot',    meaning:'nóng',   emoji:'🔥'},
      {word:'stop',   meaning:'dừng',   emoji:'🛑'},
      {word:'clock',  meaning:'đồng hồ',emoji:'🕐'},
      {word:'dollar', meaning:'đô la',  emoji:'💵'},
    ]},
  { id:'O',   label:'O',   ipa:'oʊ', type:'vowel', group:'Single Vowels',
    color:'bg-red-600',     grad:'from-red-600 to-red-800',        hard:false,
    tip:'Bắt đầu "o" rồi trượt sang "u" nhẹ — diphthong ngắn. Không phải "ô" đơn',
    words:[
      {word:'go',   meaning:'đi',        emoji:'🏃'},
      {word:'home', meaning:'nhà',       emoji:'🏠'},
      {word:'road', meaning:'con đường', emoji:'🛣️'},
      {word:'cold', meaning:'lạnh',      emoji:'🥶'},
    ]},
  { id:'E',   label:'E',   ipa:'iː', type:'vowel', group:'Single Vowels',
    color:'bg-emerald-600', grad:'from-emerald-600 to-emerald-800',hard:false,
    tip:'Âm /i/ trong các từ kết thúc bằng -y, -ey, -ie — nhẹ và ngắn hơn EE',
    words:[
      {word:'happy',  meaning:'vui vẻ',    emoji:'😊'},
      {word:'city',   meaning:'thành phố', emoji:'🏙️'},
      {word:'very',   meaning:'rất',       emoji:'💪'},
      {word:'funny',  meaning:'buồn cười', emoji:'😄'},
    ]},
  { id:'A',   label:'A',   ipa:'eɪ', type:'vowel', group:'Single Vowels',
    color:'bg-blue-600',    grad:'from-blue-600 to-blue-800',      hard:false,
    tip:'Tên chữ cái A — bắt đầu "e" trượt lên "i". Giống EY nhưng trong pattern chữ a-e',
    words:[
      {word:'name',  meaning:'tên',           emoji:'🏷️'},
      {word:'face',  meaning:'khuôn mặt',     emoji:'😊'},
      {word:'say',   meaning:'nói',           emoji:'💬'},
      {word:'place', meaning:'địa điểm',      emoji:'📍'},
    ]},

  // ════════════════════════════════════════════════════════════
  // VOWELS — Vowel Combinations (Diphthongs) · 9 sounds
  // ════════════════════════════════════════════════════════════
  { id:'EY',  label:'EY',  ipa:'eɪ', type:'vowel', group:'Diphthongs',
    color:'bg-violet-600',  grad:'from-violet-600 to-violet-800',  hard:false,
    tip:'Bắt đầu "e" rồi trượt lên "i" — như trong "say, day"',
    words:[
      {word:'say',    meaning:'nói',        emoji:'💬'},
      {word:'great',  meaning:'tuyệt vời',  emoji:'🌟'},
      {word:'make',   meaning:'làm',        emoji:'🔨'},
      {word:'table',  meaning:'cái bàn',    emoji:'🪑'},
    ]},
  { id:'ai',  label:'ai',  ipa:'aɪ', type:'vowel', group:'Diphthongs',
    color:'bg-teal-600',    grad:'from-teal-600 to-teal-800',      hard:false,
    tip:'Từ "a" rộng trượt lên "i" — như "night, like". Không phải "ây" đơn',
    words:[
      {word:'nice',  meaning:'tốt, dễ chịu',emoji:'😊'},
      {word:'bike',  meaning:'xe đạp',     emoji:'🚲'},
      {word:'night', meaning:'đêm',        emoji:'🌙'},
      {word:'right', meaning:'đúng',       emoji:'✅'},
    ]},
  { id:'OY',  label:'OY',  ipa:'ɔɪ', type:'vowel', group:'Diphthongs',
    color:'bg-indigo-600',  grad:'from-indigo-600 to-indigo-800',  hard:false,
    tip:'Từ "ô" tròn trượt lên "i" — như "boy, oil". Giống âm "oi" tiếng Việt',
    words:[
      {word:'boy',    meaning:'con trai',   emoji:'👦'},
      {word:'oil',    meaning:'dầu',        emoji:'🛢️'},
      {word:'voice',  meaning:'giọng nói',  emoji:'🎤'},
      {word:'enjoy',  meaning:'tận hưởng',  emoji:'😄'},
    ]},
  { id:'OH',  label:'OH',  ipa:'oʊ', type:'vowel', group:'Diphthongs',
    color:'bg-pink-600',    grad:'from-pink-600 to-pink-800',      hard:false,
    tip:'Từ "o" trượt sang "u" nhẹ. Đây là "long O" trong tiếng Anh',
    words:[
      {word:'old',   meaning:'già, cũ',  emoji:'👴'},
      {word:'notes', meaning:'ghi chú',  emoji:'📒'},
      {word:'phone', meaning:'điện thoại',emoji:'📱'},
      {word:'open',  meaning:'mở',       emoji:'🚪'},
    ]},
  { id:'OW',  label:'OW',  ipa:'aʊ', type:'vowel', group:'Diphthongs',
    color:'bg-cyan-600',    grad:'from-cyan-600 to-cyan-800',      hard:false,
    tip:'Từ "a" rộng trượt lên "u" — như "now, out". Không phải "ao" tiếng Việt',
    words:[
      {word:'loud',   meaning:'to, ồn ào', emoji:'📢'},
      {word:'now',    meaning:'bây giờ',   emoji:'⏰'},
      {word:'house',  meaning:'ngôi nhà',  emoji:'🏠'},
      {word:'south',  meaning:'phía nam',  emoji:'🧭'},
    ]},
  { id:'AR',  label:'AR',  ipa:'ɑːr',type:'vowel', group:'Diphthongs',
    color:'bg-teal-700',    grad:'from-teal-700 to-teal-900',      hard:false,
    tip:'Âm "a" dài + cuộn lưỡi nhẹ ra sau (giọng Mỹ). Như "car, large"',
    words:[
      {word:'car',   meaning:'xe hơi',  emoji:'🚗'},
      {word:'large', meaning:'to lớn',  emoji:'🐘'},
      {word:'start', meaning:'bắt đầu', emoji:'▶️'},
      {word:'heart', meaning:'trái tim',emoji:'❤️'},
    ]},
  { id:'OR',  label:'OR',  ipa:'ɔːr',type:'vowel', group:'Diphthongs',
    color:'bg-amber-700',   grad:'from-amber-700 to-amber-900',    hard:false,
    tip:'Âm "ô" tròn + cuộn lưỡi. Như "more, door, for"',
    words:[
      {word:'more',  meaning:'thêm',    emoji:'➕'},
      {word:'door',  meaning:'cánh cửa',emoji:'🚪'},
      {word:'story', meaning:'câu chuyện',emoji:'📖'},
      {word:'before',meaning:'trước',   emoji:'⏮️'},
    ]},
  { id:'AIR', label:'AIR', ipa:'ɛər',type:'vowel', group:'Diphthongs',
    color:'bg-orange-600',  grad:'from-orange-600 to-orange-800',  hard:false,
    tip:'Âm "e" + schwa + cuộn lưỡi. Như "where, chair, square"',
    words:[
      {word:'chair',  meaning:'cái ghế',  emoji:'🪑'},
      {word:'where',  meaning:'ở đâu',    emoji:'📍'},
      {word:'there',  meaning:'ở đó',     emoji:'👉'},
      {word:'careful',meaning:'cẩn thận', emoji:'⚠️'},
    ]},
  { id:'EAR', label:'EAR', ipa:'ɪər',type:'vowel', group:'Diphthongs',
    color:'bg-red-500',     grad:'from-red-500 to-red-700',        hard:false,
    tip:'Âm "i" ngắn + schwa + cuộn lưỡi. Như "near, here, hear"',
    words:[
      {word:'near',  meaning:'gần',       emoji:'📏'},
      {word:'here',  meaning:'ở đây',     emoji:'🏠'},
      {word:'hear',  meaning:'nghe',      emoji:'👂'},
      {word:'really',meaning:'thực sự',   emoji:'💯'},
    ]},

  // ════════════════════════════════════════════════════════════
  // CONSONANTS — Plosives · 6 sounds
  // ════════════════════════════════════════════════════════════
  { id:'P',   label:'P',   ipa:'p',  type:'consonant', group:'Plosives',
    color:'bg-fuchsia-600', grad:'from-fuchsia-600 to-fuchsia-800',hard:false,
    tip:'Khép môi hoàn toàn, tích tụ khí rồi bật ra mạnh (aspirated khi đầu từ)',
    words:[
      {word:'pretty', meaning:'xinh đẹp',emoji:'🌸'},
      {word:'plant',  meaning:'cây',     emoji:'🌿'},
      {word:'people', meaning:'người',   emoji:'👥'},
      {word:'stop',   meaning:'dừng',    emoji:'🛑'},
    ]},
  { id:'B',   label:'B',   ipa:'b',  type:'consonant', group:'Plosives',
    color:'bg-blue-600',    grad:'from-blue-600 to-blue-800',      hard:false,
    tip:'Giống P nhưng RUNG HỌng. Bật môi + rung dây thanh âm',
    words:[
      {word:'baby',  meaning:'em bé',    emoji:'👶'},
      {word:'bird',  meaning:'con chim', emoji:'🐦'},
      {word:'book',  meaning:'cuốn sách',emoji:'📖'},
      {word:'big',   meaning:'to lớn',   emoji:'🐘'},
    ]},
  { id:'T',   label:'T',   ipa:'t',  type:'consonant', group:'Plosives',
    color:'bg-emerald-600', grad:'from-emerald-600 to-emerald-800',hard:false,
    tip:'Lưỡi chạm sau răng cửa trên, bật ra. Đầu từ có hơi thở (aspirated)',
    words:[
      {word:'tiny',   meaning:'tí hon',  emoji:'🐜'},
      {word:'turtle', meaning:'rùa',     emoji:'🐢'},
      {word:'table',  meaning:'cái bàn', emoji:'🪑'},
      {word:'time',   meaning:'thời gian',emoji:'⏰'},
    ]},
  { id:'D',   label:'D',   ipa:'d',  type:'consonant', group:'Plosives',
    color:'bg-amber-600',   grad:'from-amber-600 to-amber-800',    hard:false,
    tip:'Giống T nhưng RUNG HỌng. Lưỡi chạm sau răng + rung dây thanh âm',
    words:[
      {word:'dinner', meaning:'bữa tối', emoji:'🍽️'},
      {word:'date',   meaning:'ngày tháng',emoji:'📅'},
      {word:'dog',    meaning:'con chó', emoji:'🐶'},
      {word:'deep',   meaning:'sâu',     emoji:'🌊'},
    ]},
  { id:'K',   label:'K',   ipa:'k',  type:'consonant', group:'Plosives',
    color:'bg-orange-600',  grad:'from-orange-600 to-orange-800',  hard:false,
    tip:'Lưỡi chạm vòm mềm PHÍA SAU miệng, bật ra. Đầu từ có hơi thở',
    words:[
      {word:'candy', meaning:'kẹo',     emoji:'🍬'},
      {word:'cane',  meaning:'gậy',     emoji:'🦯'},
      {word:'kind',  meaning:'tốt bụng',emoji:'💛'},
      {word:'clock', meaning:'đồng hồ', emoji:'🕐'},
    ]},
  { id:'G',   label:'G',   ipa:'g',  type:'consonant', group:'Plosives',
    color:'bg-red-600',     grad:'from-red-600 to-red-800',        hard:false,
    tip:'Giống K nhưng RUNG HỌng. Lưỡi vòm mềm + rung dây thanh âm',
    words:[
      {word:'giggly', meaning:'hay cười',emoji:'😄'},
      {word:'girl',   meaning:'con gái', emoji:'👧'},
      {word:'good',   meaning:'tốt',     emoji:'👍'},
      {word:'big',    meaning:'to lớn',  emoji:'🐘'},
    ]},

  // ════════════════════════════════════════════════════════════
  // CONSONANTS — Nasals · 3 sounds
  // ════════════════════════════════════════════════════════════
  { id:'M',   label:'M',   ipa:'m',  type:'consonant', group:'Nasals',
    color:'bg-purple-600',  grad:'from-purple-600 to-purple-800',  hard:false,
    tip:'Khép môi hoàn toàn, cho khí thoát qua MŨI. Rung cả mũi khi phát âm',
    words:[
      {word:'meek',  meaning:'hiền lành', emoji:'🕊️'},
      {word:'mouse', meaning:'con chuột', emoji:'🐭'},
      {word:'moon',  meaning:'mặt trăng', emoji:'🌙'},
      {word:'name',  meaning:'tên',       emoji:'🏷️'},
    ]},
  { id:'N',   label:'N',   ipa:'n',  type:'consonant', group:'Nasals',
    color:'bg-red-800',     grad:'from-red-800 to-red-900',        hard:false,
    tip:'Lưỡi chạm sau răng cửa trên, khí thoát qua MŨI. Không bật lưỡi',
    words:[
      {word:'new',      meaning:'mới',      emoji:'✨'},
      {word:'necklace', meaning:'vòng cổ',  emoji:'📿'},
      {word:'name',     meaning:'tên',      emoji:'🏷️'},
      {word:'night',    meaning:'đêm',      emoji:'🌙'},
    ]},
  { id:'NG',  label:'NG',  ipa:'ŋ',  type:'consonant', group:'Nasals',
    color:'bg-rose-700',    grad:'from-rose-700 to-rose-900',      hard:false,
    tip:'Lưỡi chạm vòm MỀM phía sau, khí qua mũi. Không có âm "g" riêng lẻ sau /ŋ/',
    words:[
      {word:'ring',     meaning:'chiếc nhẫn',emoji:'💍'},
      {word:'song',     meaning:'bài hát',  emoji:'🎵'},
      {word:'morning',  meaning:'buổi sáng',emoji:'🌅'},
      {word:'learning', meaning:'học hỏi',  emoji:'📚'},
    ]},

  // ════════════════════════════════════════════════════════════
  // CONSONANTS — Fricatives · 9 sounds
  // ════════════════════════════════════════════════════════════
  { id:'F',   label:'F',   ipa:'f',  type:'consonant', group:'Fricatives',
    color:'bg-green-600',   grad:'from-green-600 to-green-800',    hard:false,
    tip:'Răng cửa TRÊN đặt lên môi DƯỚI, thổi khí nhẹ. KHÔNG rung họng',
    words:[
      {word:'furry',  meaning:'có lông xù',emoji:'🐻'},
      {word:'friend', meaning:'bạn bè',    emoji:'🤝'},
      {word:'food',   meaning:'thức ăn',   emoji:'🍜'},
      {word:'phone',  meaning:'điện thoại',emoji:'📱'},
    ]},
  { id:'V',   label:'V',   ipa:'v',  type:'consonant', group:'Fricatives',
    color:'bg-blue-600',    grad:'from-blue-600 to-blue-800',      hard:true,
    tip:'Giống F nhưng RUNG HỌng. Răng trên + môi dưới + rung dây thanh. KHÔNG phải "b"!',
    words:[
      {word:'vital',     meaning:'quan trọng',emoji:'⭐'},
      {word:'vegetable', meaning:'rau củ',   emoji:'🥦'},
      {word:'voice',     meaning:'giọng nói',emoji:'🎤'},
      {word:'very',      meaning:'rất',      emoji:'💪'},
    ]},
  { id:'th',  label:'th',  ipa:'θ',  type:'consonant', group:'Fricatives',
    color:'bg-violet-600',  grad:'from-violet-600 to-violet-800',  hard:true,
    tip:'ĐẶT ĐẦU LƯỠI GIỮA HAI HÀNG RĂNG, thổi khí nhẹ KHÔNG rung họng. Khó nhất!',
    words:[
      {word:'think',    meaning:'suy nghĩ',  emoji:'💭'},
      {word:'three',    meaning:'ba',        emoji:'3️⃣'},
      {word:'bath',     meaning:'tắm',       emoji:'🛁'},
      {word:'earth',    meaning:'trái đất',  emoji:'🌍'},
    ]},
  { id:'TH',  label:'TH',  ipa:'ð',  type:'consonant', group:'Fricatives',
    color:'bg-teal-700',    grad:'from-teal-700 to-teal-900',      hard:true,
    tip:'Giống th nhưng RUNG HỌng. Lưỡi giữa răng + rung dây thanh âm',
    words:[
      {word:'this',    meaning:'cái này',  emoji:'👆'},
      {word:'mother',  meaning:'mẹ',       emoji:'👩'},
      {word:'weather', meaning:'thời tiết',emoji:'⛅'},
      {word:'breathe', meaning:'thở',      emoji:'🫁'},
    ]},
  { id:'S',   label:'S',   ipa:'s',  type:'consonant', group:'Fricatives',
    color:'bg-pink-600',    grad:'from-pink-600 to-pink-800',      hard:false,
    tip:'Đầu lưỡi gần (không chạm) sau răng cửa trên, thổi khí. Không rung họng',
    words:[
      {word:'soft',    meaning:'mềm',      emoji:'🧸'},
      {word:'sweater', meaning:'áo len',   emoji:'🧥'},
      {word:'school',  meaning:'trường',   emoji:'🏫'},
      {word:'sleep',   meaning:'ngủ',      emoji:'😴'},
    ]},
  { id:'Z',   label:'Z',   ipa:'z',  type:'consonant', group:'Fricatives',
    color:'bg-slate-600',   grad:'from-slate-600 to-slate-800',    hard:false,
    tip:'Giống S nhưng RUNG HỌng. Hay xuất hiện ở cuối từ số nhiều (-s) và động từ',
    words:[
      {word:'lazy',  meaning:'lười biếng',emoji:'😴'},
      {word:'zebra', meaning:'ngựa vằn', emoji:'🦓'},
      {word:'music', meaning:'âm nhạc',  emoji:'🎵'},
      {word:'nose',  meaning:'cái mũi',  emoji:'👃'},
    ]},
  { id:'SH',  label:'SH',  ipa:'ʃ',  type:'consonant', group:'Fricatives',
    color:'bg-fuchsia-700', grad:'from-fuchsia-700 to-fuchsia-900',hard:false,
    tip:'Chu môi nhẹ ra phía trước, thổi khí. Không rung họng. Như "ssh" khi bảo im lặng',
    words:[
      {word:'shiny', meaning:'sáng bóng',emoji:'✨'},
      {word:'shoes', meaning:'đôi giày', emoji:'👟'},
      {word:'she',   meaning:'cô ấy',   emoji:'👩'},
      {word:'wish',  meaning:'mong muốn',emoji:'⭐'},
    ]},
  { id:'ZH',  label:'ZH',  ipa:'ʒ',  type:'consonant', group:'Fricatives',
    color:'bg-red-800',     grad:'from-red-800 to-red-950',        hard:true,
    tip:'Giống SH nhưng RUNG HỌng. Ít gặp — chỉ trong "measure, treasure, vision"',
    words:[
      {word:'measure',  meaning:'đo lường',emoji:'📏'},
      {word:'treasure', meaning:'kho báu', emoji:'💎'},
      {word:'usual',    meaning:'thông thường',emoji:'📋'},
      {word:'vision',   meaning:'tầm nhìn',emoji:'👁️'},
    ]},
  { id:'H',   label:'H',   ipa:'h',  type:'consonant', group:'Fricatives',
    color:'bg-rose-600',    grad:'from-rose-600 to-rose-800',      hard:false,
    tip:'Thổi khí nhẹ từ họng, như hơi thở nhẹ. Không rung họng. Đơn giản nhất!',
    words:[
      {word:'happy', meaning:'vui vẻ',    emoji:'😊'},
      {word:'hippo', meaning:'hà mã',     emoji:'🦛'},
      {word:'home',  meaning:'nhà',       emoji:'🏠'},
      {word:'hand',  meaning:'bàn tay',   emoji:'✋'},
    ]},

  // ════════════════════════════════════════════════════════════
  // CONSONANTS — Approximants · 4 sounds
  // ════════════════════════════════════════════════════════════
  { id:'R',   label:'R',   ipa:'r',  type:'consonant', group:'Approximants',
    color:'bg-teal-600',    grad:'from-teal-600 to-teal-800',      hard:true,
    tip:'KHÔNG CHẠM LƯỠI VÀO ĐÂU — cuộn lưỡi ra sau giữa không khí, môi hơi thu tròn. Khác /l/ hoàn toàn!',
    words:[
      {word:'prickly',meaning:'gai góc',  emoji:'🌵'},
      {word:'branch', meaning:'cành cây', emoji:'🌿'},
      {word:'road',   meaning:'con đường',emoji:'🛣️'},
      {word:'really', meaning:'thực sự',  emoji:'💯'},
    ]},
  { id:'Y',   label:'Y',   ipa:'j',  type:'consonant', group:'Approximants',
    color:'bg-pink-500',    grad:'from-pink-500 to-pink-700',      hard:false,
    tip:'Lưỡi cao phía trước, miệng hé — giống "i" tiếng Việt nhưng chuyển sang nguyên âm ngay',
    words:[
      {word:'yummy',  meaning:'ngon',     emoji:'😋'},
      {word:'yogurt', meaning:'sữa chua', emoji:'🥛'},
      {word:'year',   meaning:'năm',      emoji:'📅'},
      {word:'you',    meaning:'bạn',      emoji:'👤'},
    ]},
  { id:'W',   label:'W',   ipa:'w',  type:'consonant', group:'Approximants',
    color:'bg-sky-600',     grad:'from-sky-600 to-sky-800',        hard:true,
    tip:'Chu môi tròn như chuẩn bị nói "oa", KHÔNG dùng răng. Khác /v/ hoàn toàn!',
    words:[
      {word:'wonderful',meaning:'tuyệt vời',emoji:'🌟'},
      {word:'whale',    meaning:'cá voi',  emoji:'🐋'},
      {word:'water',    meaning:'nước',    emoji:'💧'},
      {word:'world',    meaning:'thế giới',emoji:'🌍'},
    ]},
  { id:'L',   label:'L',   ipa:'l',  type:'consonant', group:'Approximants',
    color:'bg-purple-600',  grad:'from-purple-600 to-purple-800',  hard:false,
    tip:'ĐẦU LƯỠI CHẠM sau răng cửa trên. Khác /r/: lưỡi chạm một điểm cố định',
    words:[
      {word:'lemon',    meaning:'chanh',     emoji:'🍋'},
      {word:'lollipop', meaning:'kẹo mút',   emoji:'🍭'},
      {word:'light',    meaning:'ánh sáng',  emoji:'💡'},
      {word:'world',    meaning:'thế giới',  emoji:'🌍'},
    ]},

  // ════════════════════════════════════════════════════════════
  // CONSONANTS — Affricates · 2 sounds
  // ════════════════════════════════════════════════════════════
  { id:'CH',  label:'CH',  ipa:'tʃ', type:'consonant', group:'Affricates',
    color:'bg-amber-600',   grad:'from-amber-600 to-amber-800',    hard:false,
    tip:'Kết hợp /t/ + /ʃ/ liền nhau. Lưỡi chạm vòm miệng rồi bật ra với luồng khí',
    words:[
      {word:'cheddar', meaning:'phô mai',  emoji:'🧀'},
      {word:'cheese',  meaning:'phô mai',  emoji:'🧀'},
      {word:'church',  meaning:'nhà thờ',  emoji:'⛪'},
      {word:'teacher', meaning:'giáo viên',emoji:'👩‍🏫'},
    ]},
  { id:'J',   label:'J',   ipa:'dʒ', type:'consonant', group:'Affricates',
    color:'bg-orange-500',  grad:'from-orange-500 to-orange-700',  hard:false,
    tip:'Giống CH nhưng RUNG HỌng. Kết hợp /d/ + /ʒ/. Như "judge, just, magic"',
    words:[
      {word:'gentle', meaning:'nhẹ nhàng',emoji:'🕊️'},
      {word:'giant',  meaning:'khổng lồ', emoji:'🦕'},
      {word:'just',   meaning:'vừa, chỉ', emoji:'🎯'},
      {word:'enjoy',  meaning:'tận hưởng',emoji:'😄'},
    ]},

  // ════════════════════════════════════════════════════════════
  // CONSONANTS — Tap · 1 sound
  // ════════════════════════════════════════════════════════════
  { id:'DD',  label:'DD',  ipa:'ɾ',  type:'consonant', group:'Tap',
    color:'bg-violet-700',  grad:'from-violet-700 to-violet-900',  hard:true,
    tip:'Flap T — âm đặc trưng giọng Mỹ: /t/ và /d/ giữa hai nguyên âm phát âm như "d" nhanh. "butter" = "budder"',
    words:[
      {word:'muddy',  meaning:'bùn lầy',  emoji:'🌧️'},
      {word:'city',   meaning:'thành phố',emoji:'🏙️'},
      {word:'water',  meaning:'nước',     emoji:'💧'},
      {word:'better', meaning:'tốt hơn',  emoji:'⬆️'},
    ]},
]

// Grouped for the Sound Library UI
export const VOWEL_GROUPS = [
  { label: 'Single Vowels', key: 'Single Vowels', count: 14 },
  { label: 'Diphthongs',    key: 'Diphthongs',    count: 9  },
]
export const CONSONANT_GROUPS = [
  { label: 'Plosives',      key: 'Plosives',      count: 6 },
  { label: 'Nasals',        key: 'Nasals',         count: 3 },
  { label: 'Fricatives',    key: 'Fricatives',     count: 9 },
  { label: 'Approximants',  key: 'Approximants',   count: 4 },
  { label: 'Affricates',    key: 'Affricates',     count: 2 },
  { label: 'Tap',           key: 'Tap',            count: 1 },
]

// ─── SPANISH PHONEME INFO ──────────────────────────────────────────────────
// phoneme IPA → { tip (Vietnamese), hard }
export const SPANISH_PHONEME_INFO = {
  'a':  { tip: 'Âm "a" thuần — mở miệng rộng, lưỡi thấp. Không thay đổi chất âm như tiếng Anh', hard: false },
  'e':  { tip: 'Âm "ê" thuần — lưỡi giữa-cao, môi hơi kéo. Không trượt lên /i/ như tiếng Anh', hard: false },
  'i':  { tip: 'Âm "i" thuần — lưỡi cao phía trước, môi kéo sang ngang', hard: false },
  'o':  { tip: 'Âm "ô" thuần — môi tròn vừa, lưỡi giữa-sau. Không trượt lên /u/ như tiếng Anh', hard: false },
  'u':  { tip: 'Âm "u" thuần — môi tròn căng, lưỡi sau cao', hard: false },
  'ɾ':  { tip: 'Chạm nhẹ đầu lưỡi vào vòm một lần — như "đ" nhanh. Dùng khi "r" đứng giữa hai nguyên âm', hard: false },
  'r':  { tip: 'Rung đầu lưỡi nhiều lần liên tiếp (trill) — khó nhất tiếng Tây Ban Nha! Đặt lưỡi gần vòm, thổi hơi qua', hard: true },
  'x':  { tip: 'Thổi khí mạnh qua cổ họng phía sau — như hắng giọng. Âm này không có trong tiếng Việt!', hard: true },
  'ɲ':  { tip: 'Giống "nh" trong tiếng Việt — lưỡi chạm vòm giữa, âm mũi. Dễ với người Việt!', hard: false },
  'j':  { tip: 'Âm "y" (bán nguyên âm) — lưỡi cao phía trước, không chạm vòm. Như "y" trong "yes"', hard: false },
  'β':  { tip: 'Môi trên và môi dưới gần nhau, thổi hơi qua khe giữa — nhẹ hơn /b/ tiếng Việt', hard: true },
  'tʃ': { tip: 'Âm "ch" — lưỡi chạm vòm rồi mở ra thổi. Như "ch" trong tiếng Anh "church"', hard: false },
  'n':  { tip: 'Đầu lưỡi chạm sau răng cửa trên, âm mũi — như "n" tiếng Việt', hard: false },
  'm':  { tip: 'Khép môi, rung âm mũi — như "m" tiếng Việt', hard: false },
  'l':  { tip: 'Đầu lưỡi chạm sau răng trên — như "l" tiếng Việt', hard: false },
  'p':  { tip: 'Bật môi — ít bật hơi hơn tiếng Anh, gần giống "p" tiếng Việt', hard: false },
  'b':  { tip: 'Bật môi, rung họng — như "b" tiếng Việt', hard: false },
  't':  { tip: 'Lưỡi chạm sau răng (dental) — như "t" tiếng Việt, không bật hơi', hard: false },
  'd':  { tip: 'Lưỡi chạm sau răng, rung họng — như "đ" tiếng Việt', hard: false },
  'k':  { tip: 'Lưỡi chạm vòm mềm, bật ra — như "c/k" tiếng Việt', hard: false },
  'g':  { tip: 'Lưỡi chạm vòm mềm, rung họng — như "g" tiếng Việt', hard: false },
  'f':  { tip: 'Răng trên đặt lên môi dưới, thổi khí — như "ph" tiếng Việt', hard: false },
  's':  { tip: 'Đầu lưỡi gần răng, thổi khí — như "s/x" tiếng Việt', hard: false },
  'ʎ':  { tip: 'Lưỡi phẳng chạm vòm giữa, âm bên — như "l" nhưng lưỡi rộng hơn', hard: true },
  'gw': { tip: 'Âm "gu" — /g/ + bán nguyên âm /w/', hard: false },
  'je': { tip: 'Diphthong ie — /j/ trượt thành /e/, miệng mở dần', hard: false },
  'h':  { tip: 'Câm trong tiếng Tây Ban Nha — không phát âm', hard: false },
}

// ─── SPANISH SOUNDS (18 âm) ───────────────────────────────────────────────
export const SPANISH_SOUNDS = [
  // ════ NGUYÊN ÂM ═══════════════════════════════════════════
  { id:'ES_A', label:'a', ipa:'a', type:'vowel', group:'Nguyên Âm',
    color:'bg-red-700', grad:'from-red-700 to-red-900', hard:false,
    tip:'Âm "a" thuần — mở miệng rộng, lưỡi thấp phẳng. Ngắn và rõ, không thay đổi chất âm',
    words:[
      {word:'casa',  meaning:'ngôi nhà', emoji:'🏠', phonemes:[['c','k'],['a','a'],['s','s'],['a','a']]},
      {word:'mano',  meaning:'bàn tay',  emoji:'✋', phonemes:[['m','m'],['a','a'],['n','n'],['o','o']]},
      {word:'sala',  meaning:'phòng khách',emoji:'🛋️', phonemes:[['s','s'],['a','a'],['l','l'],['a','a']]},
    ]},
  { id:'ES_E', label:'e', ipa:'e', type:'vowel', group:'Nguyên Âm',
    color:'bg-pink-600', grad:'from-pink-600 to-pink-800', hard:false,
    tip:'Âm "ê" thuần — lưỡi giữa-cao, không trượt. Khác tiếng Anh: không biến thành /eɪ/',
    words:[
      {word:'mesa',  meaning:'cái bàn',  emoji:'🪑', phonemes:[['m','m'],['e','e'],['s','s'],['a','a']]},
      {word:'verde', meaning:'màu xanh lá',emoji:'🟢', phonemes:[['v','β'],['e','e'],['r','ɾ'],['d','d'],['e','e']]},
      {word:'tres',  meaning:'số ba',    emoji:'3️⃣', phonemes:[['tr','tr'],['e','e'],['s','s']]},
    ]},
  { id:'ES_I', label:'i', ipa:'i', type:'vowel', group:'Nguyên Âm',
    color:'bg-purple-700', grad:'from-purple-700 to-purple-900', hard:false,
    tip:'Âm "i" thuần — lưỡi cao phía trước. Sạch hơn /iː/ tiếng Anh: ngắn và nhất quán',
    words:[
      {word:'libro',  meaning:'cuốn sách',emoji:'📖', phonemes:[['l','l'],['i','i'],['br','βr'],['o','o']]},
      {word:'piso',   meaning:'tầng/sàn', emoji:'🏢', phonemes:[['p','p'],['i','i'],['s','s'],['o','o']]},
      {word:'rico',   meaning:'ngon/giàu',emoji:'😋', phonemes:[['r','ɾ'],['i','i'],['c','k'],['o','o']]},
    ]},
  { id:'ES_O', label:'o', ipa:'o', type:'vowel', group:'Nguyên Âm',
    color:'bg-teal-600', grad:'from-teal-600 to-teal-800', hard:false,
    tip:'Âm "ô" thuần — môi tròn vừa, lưỡi giữa-sau. Không trượt lên /u/ như "go" tiếng Anh',
    words:[
      {word:'boca',  meaning:'cái miệng',emoji:'👄', phonemes:[['b','b'],['o','o'],['c','k'],['a','a']]},
      {word:'moto',  meaning:'xe máy',   emoji:'🏍️', phonemes:[['m','m'],['o','o'],['t','t'],['o','o']]},
      {word:'sol',   meaning:'mặt trời', emoji:'☀️', phonemes:[['s','s'],['o','o'],['l','l']]},
    ]},
  { id:'ES_U', label:'u', ipa:'u', type:'vowel', group:'Nguyên Âm',
    color:'bg-cyan-600', grad:'from-cyan-600 to-cyan-800', hard:false,
    tip:'Âm "u" thuần — môi tròn căng, lưỡi sau. Sạch và ngắn hơn /uː/ tiếng Anh',
    words:[
      {word:'luna',  meaning:'mặt trăng',emoji:'🌙', phonemes:[['l','l'],['u','u'],['n','n'],['a','a']]},
      {word:'mucho', meaning:'rất nhiều',emoji:'💯', phonemes:[['m','m'],['u','u'],['ch','tʃ'],['o','o']]},
      {word:'gusto', meaning:'niềm vui', emoji:'😊', phonemes:[['g','g'],['u','u'],['s','s'],['t','t'],['o','o']]},
    ]},
  // ════ PHỤ ÂM THÔNG THƯỜNG ══════════════════════════════════
  { id:'ES_N', label:'n', ipa:'n', type:'consonant', group:'Phụ Âm Thông Thường',
    color:'bg-blue-700', grad:'from-blue-700 to-blue-900', hard:false,
    tip:'Đầu lưỡi chạm sau răng cửa trên, âm mũi — như "n" tiếng Việt',
    words:[
      {word:'nada',  meaning:'không gì', emoji:'🚫', phonemes:[['n','n'],['a','a'],['d','d'],['a','a']]},
      {word:'pan',   meaning:'bánh mì',  emoji:'🍞', phonemes:[['p','p'],['a','a'],['n','n']]},
      {word:'noche', meaning:'đêm tối',  emoji:'🌙', phonemes:[['n','n'],['o','o'],['ch','tʃ'],['e','e']]},
    ]},
  { id:'ES_L', label:'l', ipa:'l', type:'consonant', group:'Phụ Âm Thông Thường',
    color:'bg-indigo-700', grad:'from-indigo-700 to-indigo-900', hard:false,
    tip:'Đầu lưỡi chạm sau răng trên — giống "l" tiếng Việt nhưng rõ hơn ở cuối từ',
    words:[
      {word:'largo', meaning:'dài',      emoji:'📏', phonemes:[['l','l'],['a','a'],['r','ɾ'],['g','g'],['o','o']]},
      {word:'bola',  meaning:'quả bóng', emoji:'⚽', phonemes:[['b','b'],['o','o'],['l','l'],['a','a']]},
      {word:'sol',   meaning:'mặt trời', emoji:'☀️', phonemes:[['s','s'],['o','o'],['l','l']]},
    ]},
  { id:'ES_CH', label:'ch', ipa:'tʃ', type:'consonant', group:'Phụ Âm Thông Thường',
    color:'bg-green-700', grad:'from-green-700 to-green-900', hard:false,
    tip:'Âm "ch" — lưỡi chạm vòm rồi mở ra thổi hơi. Như "ch" tiếng Anh nhưng không bật mạnh',
    words:[
      {word:'chico', meaning:'cậu bé',   emoji:'👦', phonemes:[['ch','tʃ'],['i','i'],['c','k'],['o','o']]},
      {word:'leche', meaning:'sữa',      emoji:'🥛', phonemes:[['l','l'],['e','e'],['ch','tʃ'],['e','e']]},
      {word:'noche', meaning:'buổi tối', emoji:'🌙', phonemes:[['n','n'],['o','o'],['ch','tʃ'],['e','e']]},
    ]},
  // ════ PHỤ ÂM ĐẶC BIỆT ══════════════════════════════════════
  { id:'ES_R1', label:'r', ipa:'ɾ', type:'consonant', group:'Phụ Âm Đặc Biệt',
    color:'bg-amber-600', grad:'from-amber-600 to-amber-800', hard:false,
    tip:'Tap r — chạm nhẹ đầu lưỡi vào vòm một lần. Dùng khi "r" đứng giữa nguyên âm, ngắn và nhẹ',
    words:[
      {word:'cara',  meaning:'khuôn mặt',emoji:'😊', phonemes:[['c','k'],['a','a'],['r','ɾ'],['a','a']]},
      {word:'pero',  meaning:'nhưng',    emoji:'↔️', phonemes:[['p','p'],['e','e'],['r','ɾ'],['o','o']]},
      {word:'caro',  meaning:'đắt tiền', emoji:'💰', phonemes:[['c','k'],['a','a'],['r','ɾ'],['o','o']]},
    ]},
  { id:'ES_RR', label:'rr', ipa:'r', type:'consonant', group:'Phụ Âm Đặc Biệt',
    color:'bg-orange-700', grad:'from-orange-700 to-orange-900', hard:true,
    tip:'Trill r — rung đầu lưỡi nhiều lần liên tiếp. Âm khó nhất! Tập bằng cách nói "ddddd" nhanh với lưỡi gần vòm',
    words:[
      {word:'perro',  meaning:'con chó',  emoji:'🐕', phonemes:[['p','p'],['e','e'],['rr','r'],['o','o']]},
      {word:'tierra', meaning:'đất đai',  emoji:'🌍', phonemes:[['t','t'],['ie','je'],['rr','r'],['a','a']]},
      {word:'carro',  meaning:'xe hơi',   emoji:'🚗', phonemes:[['c','k'],['a','a'],['rr','r'],['o','o']]},
    ]},
  { id:'ES_J', label:'j', ipa:'x', type:'consonant', group:'Phụ Âm Đặc Biệt',
    color:'bg-rose-700', grad:'from-rose-700 to-rose-900', hard:true,
    tip:'Velar fricative — thổi khí mạnh qua cổ họng phía sau, như hắng giọng. Không có trong tiếng Việt!',
    words:[
      {word:'jamón', meaning:'giăm bông', emoji:'🍖', phonemes:[['j','x'],['a','a'],['m','m'],['ó','o'],['n','n']]},
      {word:'ojo',   meaning:'con mắt',   emoji:'👁️', phonemes:[['o','o'],['j','x'],['o','o']]},
      {word:'rojo',  meaning:'màu đỏ',    emoji:'🔴', phonemes:[['r','ɾ'],['o','o'],['j','x'],['o','o']]},
    ]},
  { id:'ES_Ñ', label:'ñ', ipa:'ɲ', type:'consonant', group:'Phụ Âm Đặc Biệt',
    color:'bg-violet-700', grad:'from-violet-700 to-violet-900', hard:false,
    tip:'Palatal nasal — như "nh" trong tiếng Việt (nhà, nhớ). Dễ với người Việt! Lưỡi chạm vòm giữa + âm mũi',
    words:[
      {word:'niño',  meaning:'đứa trẻ',  emoji:'👦', phonemes:[['n','n'],['i','i'],['ñ','ɲ'],['o','o']]},
      {word:'año',   meaning:'năm',      emoji:'📅', phonemes:[['a','a'],['ñ','ɲ'],['o','o']]},
      {word:'baño',  meaning:'phòng tắm',emoji:'🚿', phonemes:[['b','b'],['a','a'],['ñ','ɲ'],['o','o']]},
    ]},
  { id:'ES_Y', label:'y/ll', ipa:'j', type:'consonant', group:'Phụ Âm Đặc Biệt',
    color:'bg-emerald-700', grad:'from-emerald-700 to-emerald-900', hard:false,
    tip:'Palatal glide — như âm "y" trong tiếng Anh "yes". Trong tiếng Tây Ban Nha hiện đại, "ll" và "y" phát âm như nhau',
    words:[
      {word:'ya',    meaning:'rồi/đã',   emoji:'✅', phonemes:[['y','j'],['a','a']]},
      {word:'mayo',  meaning:'tháng 5',  emoji:'🗓️', phonemes:[['m','m'],['a','a'],['y','j'],['o','o']]},
      {word:'llama', meaning:'ngọn lửa', emoji:'🔥', phonemes:[['ll','j'],['a','a'],['m','m'],['a','a']]},
    ]},
]

export const SPANISH_VOWEL_GROUPS    = [{ key:'Nguyên Âm',         label:'Nguyên Âm · 5 âm thuần' }]
export const SPANISH_CONSONANT_GROUPS = [
  { key:'Phụ Âm Thông Thường', label:'Phụ Âm Thông Thường' },
  { key:'Phụ Âm Đặc Biệt',    label:'Phụ Âm Đặc Biệt ★' },
]

// ─── ITALIAN PHONEME INFO ──────────────────────────────────────────────────
export const ITALIAN_PHONEME_INFO = {
  'a':  { tip: 'Âm "a" thuần — mở miệng rộng, lưỡi thấp. Giống "a" tiếng Việt', hard: false },
  'e':  { tip: 'Âm "ê" — có thể đóng /e/ hoặc mở /ɛ/ tùy từ. Ngắn và rõ ràng', hard: false },
  'i':  { tip: 'Âm "i" thuần — lưỡi cao phía trước, môi kéo sang ngang', hard: false },
  'o':  { tip: 'Âm "ô" — có thể đóng /o/ hoặc mở /ɔ/ tùy từ', hard: false },
  'u':  { tip: 'Âm "u" thuần — môi tròn căng, lưỡi sau', hard: false },
  'r':  { tip: 'Trill r — rung đầu lưỡi vào vòm 1-2 lần. Nhẹ hơn tiếng Tây Ban Nha nhưng vẫn phải rung!', hard: true },
  'ʎ':  { tip: 'Palatal lateral — lưỡi phẳng rộng chạm vòm miệng, âm bên. Như "lj" nói rất nhanh. Không có trong tiếng Việt!', hard: true },
  'ɲ':  { tip: 'Palatal nasal — như "nh" trong tiếng Việt (nhà, nhớ). Dễ với người Việt!', hard: false },
  'ts': { tip: 'Affricate ts — bắt đầu /t/ rồi chuyển ngay sang /s/. Như "c" trong "pizza" đọc "pit-tsa"', hard: true },
  'dz': { tip: 'Affricate dz — bắt đầu /d/ rồi chuyển sang /z/. Biến thể rung của /ts/', hard: true },
  'ʃ':  { tip: 'Âm "sh" — chu môi nhẹ, thổi hơi. Như "sc" trước "e/i" trong tiếng Ý', hard: false },
  'tʃ': { tip: 'Affricate ch — như "ch" tiếng Anh "church". "ci" trước nguyên âm = /tʃ/', hard: false },
  'dʒ': { tip: 'Affricate dj — như "j" tiếng Anh "judge". "gi" trước nguyên âm = /dʒ/', hard: false },
  'n':  { tip: 'Đầu lưỡi chạm sau răng, âm mũi — như "n" tiếng Việt', hard: false },
  'm':  { tip: 'Khép môi, rung âm mũi — như "m" tiếng Việt', hard: false },
  'l':  { tip: 'Đầu lưỡi chạm sau răng trên, âm bên — như "l" tiếng Việt', hard: false },
  'p':  { tip: 'Bật môi không bật hơi — như "p" tiếng Việt', hard: false },
  'b':  { tip: 'Bật môi, rung họng — như "b" tiếng Việt', hard: false },
  't':  { tip: 'Lưỡi chạm sau răng (dental), không bật hơi — như "t" tiếng Việt', hard: false },
  'd':  { tip: 'Lưỡi chạm sau răng, rung họng — như "đ" tiếng Việt', hard: false },
  'k':  { tip: 'Lưỡi chạm vòm mềm, bật ra — như "c/k" tiếng Việt', hard: false },
  'g':  { tip: 'Lưỡi chạm vòm mềm, rung họng — như "g" tiếng Việt', hard: false },
  'f':  { tip: 'Răng trên + môi dưới, thổi khí — như "ph" tiếng Việt', hard: false },
  'v':  { tip: 'Răng trên + môi dưới, rung họng — như "v" tiếng Việt', hard: false },
  's':  { tip: 'Đầu lưỡi gần răng, thổi khí — như "s/x" tiếng Việt', hard: false },
  'z':  { tip: 'Như /s/ nhưng rung họng — như "d" tiếng Việt trong một số thổ ngữ', hard: false },
  'j':  { tip: 'Bán nguyên âm "y" — lưỡi cao phía trước', hard: false },
  'w':  { tip: 'Bán nguyên âm "u" — môi tròn căng', hard: false },
}

// ─── ITALIAN SOUNDS (17 âm) ───────────────────────────────────────────────
export const ITALIAN_SOUNDS = [
  // ════ NGUYÊN ÂM ═══════════════════════════════════════════
  { id:'IT_A', label:'a', ipa:'a', type:'vowel', group:'Nguyên Âm',
    color:'bg-red-700', grad:'from-red-700 to-red-900', hard:false,
    tip:'Âm "a" thuần — mở miệng rộng, lưỡi thấp. Giống "a" tiếng Việt, ngắn và rõ',
    words:[
      {word:'casa',  meaning:'ngôi nhà', emoji:'🏠', phonemes:[['c','k'],['a','a'],['s','s'],['a','a']]},
      {word:'mare',  meaning:'biển',     emoji:'🌊', phonemes:[['m','m'],['a','a'],['r','r'],['e','e']]},
      {word:'padre', meaning:'cha/bố',   emoji:'👨', phonemes:[['p','p'],['a','a'],['dr','dr'],['e','e']]},
    ]},
  { id:'IT_E', label:'e', ipa:'e', type:'vowel', group:'Nguyên Âm',
    color:'bg-pink-600', grad:'from-pink-600 to-pink-800', hard:false,
    tip:'Âm "ê" — có thể đóng /e/ hoặc mở /ɛ/ tùy từ. Ngắn và rõ, không trượt như tiếng Anh',
    words:[
      {word:'bene',  meaning:'tốt lắm',  emoji:'👍', phonemes:[['b','b'],['e','e'],['n','n'],['e','e']]},
      {word:'verde', meaning:'màu xanh lá',emoji:'🟢', phonemes:[['v','v'],['e','e'],['r','r'],['d','d'],['e','e']]},
      {word:'sera',  meaning:'buổi tối', emoji:'🌆', phonemes:[['s','s'],['e','e'],['r','r'],['a','a']]},
    ]},
  { id:'IT_I', label:'i', ipa:'i', type:'vowel', group:'Nguyên Âm',
    color:'bg-purple-700', grad:'from-purple-700 to-purple-900', hard:false,
    tip:'Âm "i" thuần — lưỡi cao phía trước. Ngắn và rõ ràng',
    words:[
      {word:'vino',   meaning:'rượu vang',emoji:'🍷', phonemes:[['v','v'],['i','i'],['n','n'],['o','o']]},
      {word:'libro',  meaning:'cuốn sách',emoji:'📖', phonemes:[['l','l'],['i','i'],['br','br'],['o','o']]},
      {word:'amico',  meaning:'bạn bè',   emoji:'🤝', phonemes:[['a','a'],['m','m'],['i','i'],['c','k'],['o','o']]},
    ]},
  { id:'IT_O', label:'o', ipa:'o', type:'vowel', group:'Nguyên Âm',
    color:'bg-teal-600', grad:'from-teal-600 to-teal-800', hard:false,
    tip:'Âm "ô" — môi tròn, lưỡi giữa-sau. Ngắn và thuần, không trượt lên /u/ như tiếng Anh',
    words:[
      {word:'sole',  meaning:'mặt trời', emoji:'☀️', phonemes:[['s','s'],['o','o'],['l','l'],['e','e']]},
      {word:'bello', meaning:'đẹp',      emoji:'😍', phonemes:[['b','b'],['e','e'],['ll','l'],['o','o']]},
      {word:'modo',  meaning:'cách thức',emoji:'💡', phonemes:[['m','m'],['o','o'],['d','d'],['o','o']]},
    ]},
  { id:'IT_U', label:'u', ipa:'u', type:'vowel', group:'Nguyên Âm',
    color:'bg-cyan-600', grad:'from-cyan-600 to-cyan-800', hard:false,
    tip:'Âm "u" thuần — môi tròn căng, lưỡi sau. Ngắn và rõ hơn /uː/ tiếng Anh',
    words:[
      {word:'uno',   meaning:'số một',   emoji:'1️⃣', phonemes:[['u','u'],['n','n'],['o','o']]},
      {word:'luna',  meaning:'mặt trăng',emoji:'🌙', phonemes:[['l','l'],['u','u'],['n','n'],['a','a']]},
      {word:'buono', meaning:'ngon/tốt', emoji:'😋', phonemes:[['b','b'],['uo','wo'],['n','n'],['o','o']]},
    ]},
  // ════ PHỤ ÂM THÔNG THƯỜNG ══════════════════════════════════
  { id:'IT_SC', label:'sc', ipa:'ʃ', type:'consonant', group:'Phụ Âm Thông Thường',
    color:'bg-blue-700', grad:'from-blue-700 to-blue-900', hard:false,
    tip:'"sc" trước e/i = âm "sh". Chu môi nhẹ, thổi hơi qua — như "sh" trong tiếng Anh',
    words:[
      {word:'pesce',  meaning:'con cá',   emoji:'🐟', phonemes:[['p','p'],['e','e'],['sc','ʃ'],['e','e']]},
      {word:'scena',  meaning:'cảnh/sân khấu',emoji:'🎭', phonemes:[['sc','ʃ'],['e','e'],['n','n'],['a','a']]},
      {word:'uscire', meaning:'ra ngoài', emoji:'🚪', phonemes:[['u','u'],['sc','ʃ'],['i','i'],['r','r'],['e','e']]},
    ]},
  { id:'IT_CI', label:'ci/ce', ipa:'tʃ', type:'consonant', group:'Phụ Âm Thông Thường',
    color:'bg-green-700', grad:'from-green-700 to-green-900', hard:false,
    tip:'"c" trước i/e = /tʃ/ như "ch" tiếng Anh. Lưỡi chạm vòm, mở ra thổi — dễ nhớ!',
    words:[
      {word:'ciao',  meaning:'xin chào',  emoji:'👋', phonemes:[['c','tʃ'],['ia','ja'],['o','o']]},
      {word:'cena',  meaning:'bữa tối',   emoji:'🍽️', phonemes:[['c','tʃ'],['e','e'],['n','n'],['a','a']]},
      {word:'cielo', meaning:'bầu trời',  emoji:'☁️', phonemes:[['c','tʃ'],['ie','je'],['l','l'],['o','o']]},
    ]},
  // ════ PHỤ ÂM ĐẶC BIỆT ══════════════════════════════════════
  { id:'IT_R', label:'r', ipa:'r', type:'consonant', group:'Phụ Âm Đặc Biệt',
    color:'bg-orange-700', grad:'from-orange-700 to-orange-900', hard:true,
    tip:'Trill r — rung đầu lưỡi 1-2 lần vào vòm. Nhẹ hơn tiếng Tây Ban Nha nhưng phải rung. Khác hoàn toàn /r/ tiếng Anh!',
    words:[
      {word:'rosso', meaning:'màu đỏ',   emoji:'🔴', phonemes:[['r','r'],['o','o'],['ss','s'],['o','o']]},
      {word:'raro',  meaning:'hiếm gặp', emoji:'💎', phonemes:[['r','r'],['a','a'],['r','r'],['o','o']]},
      {word:'terra', meaning:'đất đai',  emoji:'🌍', phonemes:[['t','t'],['e','e'],['rr','r'],['a','a']]},
    ]},
  { id:'IT_GLI', label:'gli', ipa:'ʎ', type:'consonant', group:'Phụ Âm Đặc Biệt',
    color:'bg-rose-700', grad:'from-rose-700 to-rose-900', hard:true,
    tip:'Palatal lateral — lưỡi rộng phẳng chạm vòm giữa, âm bên. Như "lj" nói rất nhanh. Không có trong tiếng Việt!',
    words:[
      {word:'figlio', meaning:'con trai', emoji:'👦', phonemes:[['f','f'],['i','i'],['gli','ʎ'],['o','o']]},
      {word:'meglio', meaning:'tốt hơn', emoji:'⬆️', phonemes:[['m','m'],['e','e'],['gli','ʎ'],['o','o']]},
      {word:'luglio', meaning:'tháng 7', emoji:'📅', phonemes:[['l','l'],['u','u'],['gli','ʎ'],['o','o']]},
    ]},
  { id:'IT_GN', label:'gn', ipa:'ɲ', type:'consonant', group:'Phụ Âm Đặc Biệt',
    color:'bg-violet-700', grad:'from-violet-700 to-violet-900', hard:false,
    tip:'"gn" = /ɲ/ — như "nh" trong tiếng Việt (nhà, nhớ). Dễ với người Việt! Lưỡi chạm vòm giữa + âm mũi',
    words:[
      {word:'bagno',   meaning:'phòng tắm',emoji:'🚿', phonemes:[['b','b'],['a','a'],['gn','ɲ'],['o','o']]},
      {word:'ogni',    meaning:'mỗi',      emoji:'🔄', phonemes:[['o','o'],['gn','ɲ'],['i','i']]},
      {word:'gnocchi', meaning:'gnocchi',  emoji:'🍝', phonemes:[['gn','ɲ'],['o','o'],['cc','k'],['hi','i']]},
    ]},
  { id:'IT_Z', label:'z', ipa:'ts', type:'consonant', group:'Phụ Âm Đặc Biệt',
    color:'bg-amber-700', grad:'from-amber-700 to-amber-900', hard:true,
    tip:'"z" = /ts/ hoặc /dz/ — bắt đầu /t/ rồi chuyển ngay sang /s/. Như "c" trong "pizza" = "pit-tsa"',
    words:[
      {word:'pizza',  meaning:'pizza',    emoji:'🍕', phonemes:[['p','p'],['i','i'],['zz','ts'],['a','a']]},
      {word:'zero',   meaning:'số không', emoji:'0️⃣', phonemes:[['z','dz'],['e','e'],['r','r'],['o','o']]},
      {word:'forza',  meaning:'sức mạnh', emoji:'💪', phonemes:[['f','f'],['o','o'],['r','r'],['z','ts'],['a','a']]},
    ]},
  { id:'IT_GI', label:'gi/ge', ipa:'dʒ', type:'consonant', group:'Phụ Âm Đặc Biệt',
    color:'bg-emerald-700', grad:'from-emerald-700 to-emerald-900', hard:false,
    tip:'"g" trước i/e = /dʒ/ như "j" tiếng Anh "judge". Lưỡi chạm vòm, rung họng',
    words:[
      {word:'giorno', meaning:'ngày',     emoji:'📅', phonemes:[['gi','dʒ'],['o','o'],['r','r'],['n','n'],['o','o']]},
      {word:'gente',  meaning:'người',    emoji:'👥', phonemes:[['g','dʒ'],['e','e'],['n','n'],['t','t'],['e','e']]},
      {word:'viaggio',meaning:'chuyến đi',emoji:'✈️', phonemes:[['v','v'],['ia','ja'],['ggi','dʒ'],['o','o']]},
    ]},
]

export const ITALIAN_VOWEL_GROUPS    = [{ key:'Nguyên Âm',         label:'Nguyên Âm · 5 âm thuần' }]
export const ITALIAN_CONSONANT_GROUPS = [
  { key:'Phụ Âm Thông Thường', label:'Phụ Âm Thông Thường' },
  { key:'Phụ Âm Đặc Biệt',    label:'Phụ Âm Đặc Biệt ★' },
]
