// ─── SOUND LIBRARY (48 phonemes) ─────────────────────────────────────────
// Mirrors ELSA Speak's Sound Library structure

export const SOUNDS = [
  // ════════════════════════════════════════════════════════════
  // VOWELS — Single Vowels (Monophthongs) · 14 sounds
  // ════════════════════════════════════════════════════════════
  { id:'EE',  label:'EE',  ipa:'iː', type:'vowel', group:'Single Vowels',
    color:'bg-red-700',     grad:'from-red-700 to-red-900',       hard:false,
    tip:'Kéo hai góc môi sang ngang, lưỡi cao và căng về phía trước miệng',
    words:[
      {word:'bee',   meaning:'con ong',     emoji:'🐝'},
      {word:'tree',  meaning:'cây',         emoji:'🌳'},
      {word:'feet',  meaning:'bàn chân',    emoji:'🦶'},
      {word:'sleep', meaning:'ngủ',         emoji:'😴'},
    ]},
  { id:'IH',  label:'IH',  ipa:'ɪ',  type:'vowel', group:'Single Vowels',
    color:'bg-pink-600',    grad:'from-pink-600 to-pink-800',      hard:false,
    tip:'Âm /i/ ngắn — lưỡi cao nhưng miệng thư giãn hơn EE, KHÔNG kéo căng môi',
    words:[
      {word:'fish',  meaning:'cá',          emoji:'🐟'},
      {word:'sit',   meaning:'ngồi',        emoji:'🪑'},
      {word:'bit',   meaning:'miếng nhỏ',   emoji:'🧩'},
      {word:'quick', meaning:'nhanh',       emoji:'⚡'},
    ]},
  { id:'EH',  label:'EH',  ipa:'ɛ',  type:'vowel', group:'Single Vowels',
    color:'bg-purple-700',  grad:'from-purple-700 to-purple-900',  hard:false,
    tip:'Âm "e" ngắn — miệng hé vừa, lưỡi giữa. Khác EE: không kéo môi',
    words:[
      {word:'red',    meaning:'màu đỏ',     emoji:'🔴'},
      {word:'bed',    meaning:'cái giường', emoji:'🛏️'},
      {word:'egg',    meaning:'quả trứng',  emoji:'🥚'},
      {word:'friend', meaning:'bạn bè',     emoji:'🤝'},
    ]},
  { id:'AA',  label:'AA',  ipa:'æ',  type:'vowel', group:'Single Vowels',
    color:'bg-indigo-700',  grad:'from-indigo-700 to-indigo-900',  hard:true,
    tip:'Mở miệng RỘNG hơn EH, kéo về phía trước — "ê-a" kết hợp nhanh. Khó với người Việt!',
    words:[
      {word:'cat',  meaning:'con mèo',  emoji:'🐱'},
      {word:'bag',  meaning:'cái túi',  emoji:'👜'},
      {word:'hand', meaning:'bàn tay',  emoji:'✋'},
      {word:'black',meaning:'màu đen',  emoji:'⬛'},
    ]},
  { id:'UH',  label:'UH',  ipa:'ʌ',  type:'vowel', group:'Single Vowels',
    color:'bg-teal-600',    grad:'from-teal-600 to-teal-800',      hard:true,
    tip:'Giống "ă" tiếng Việt — miệng mở vừa, lưỡi giữa-thấp. KHÔNG phải "ơ" hay "a"',
    words:[
      {word:'cup',  meaning:'cái tách', emoji:'☕'},
      {word:'bus',  meaning:'xe buýt',  emoji:'🚌'},
      {word:'duck', meaning:'con vịt',  emoji:'🦆'},
      {word:'run',  meaning:'chạy',     emoji:'🏃'},
    ]},
  { id:'uh',  label:'uh',  ipa:'ə',  type:'vowel', group:'Single Vowels',
    color:'bg-blue-700',    grad:'from-blue-700 to-blue-900',      hard:false,
    tip:'Schwa — âm trung hòa nhất, miệng HOÀN TOÀN thư giãn. Âm phổ biến nhất trong tiếng Anh!',
    words:[
      {word:'about',  meaning:'về',         emoji:'💭'},
      {word:'today',  meaning:'hôm nay',    emoji:'📅'},
      {word:'problem',meaning:'vấn đề',     emoji:'🤔'},
      {word:'banana', meaning:'chuối',      emoji:'🍌'},
    ]},
  { id:'ER',  label:'ER',  ipa:'ɜː', type:'vowel', group:'Single Vowels',
    color:'bg-fuchsia-600', grad:'from-fuchsia-600 to-fuchsia-800',hard:true,
    tip:'Môi tròn nhẹ, lưỡi giữa không chạm đâu, cuộn ra sau (giọng Mỹ). Khác "ơ" Việt: cuộn lưỡi!',
    words:[
      {word:'bird', meaning:'con chim',  emoji:'🐦'},
      {word:'word', meaning:'từ',        emoji:'📝'},
      {word:'learn',meaning:'học',       emoji:'📚'},
      {word:'turn', meaning:'quay lại',  emoji:'🔄'},
    ]},
  { id:'OO',  label:'OO',  ipa:'uː', type:'vowel', group:'Single Vowels',
    color:'bg-cyan-600',    grad:'from-cyan-600 to-cyan-800',      hard:false,
    tip:'Âm "u" dài — môi tròn căng, đẩy ra phía trước. Kéo dài hơn âm "u" tiếng Việt',
    words:[
      {word:'food',  meaning:'thức ăn',     emoji:'🍜'},
      {word:'moon',  meaning:'mặt trăng',   emoji:'🌙'},
      {word:'school',meaning:'trường học',  emoji:'🏫'},
      {word:'blue',  meaning:'màu xanh dương',emoji:'🔵'},
    ]},
  { id:'U',   label:'U',   ipa:'ʊ',  type:'vowel', group:'Single Vowels',
    color:'bg-green-700',   grad:'from-green-700 to-green-900',    hard:true,
    tip:'Âm "u" NGẮN — môi tròn nhẹ, KHÔNG căng. Khác OO: ngắn hơn và tối hơn',
    words:[
      {word:'book', meaning:'cuốn sách',emoji:'📖'},
      {word:'good', meaning:'tốt',      emoji:'👍'},
      {word:'look', meaning:'nhìn',     emoji:'👀'},
      {word:'put',  meaning:'đặt',      emoji:'👇'},
    ]},
  { id:'AW',  label:'AW',  ipa:'ɔː', type:'vowel', group:'Single Vowels',
    color:'bg-amber-600',   grad:'from-amber-600 to-amber-800',    hard:false,
    tip:'Môi tròn vừa, miệng mở. Giống "o" trong "Ông" nhưng dài hơn',
    words:[
      {word:'call',  meaning:'gọi',     emoji:'📞'},
      {word:'ball',  meaning:'quả bóng',emoji:'⚽'},
      {word:'water', meaning:'nước',    emoji:'💧'},
      {word:'small', meaning:'nhỏ',     emoji:'🔹'},
    ]},
  { id:'AH',  label:'AH',  ipa:'ɑː', type:'vowel', group:'Single Vowels',
    color:'bg-orange-600',  grad:'from-orange-600 to-orange-800',  hard:false,
    tip:'Mở miệng RỘNG nhất, lưỡi thấp phía sau. Giống "a" trong "cha"',
    words:[
      {word:'hot',    meaning:'nóng',   emoji:'🔥'},
      {word:'stop',   meaning:'dừng',   emoji:'🛑'},
      {word:'clock',  meaning:'đồng hồ',emoji:'🕐'},
      {word:'dollar', meaning:'đô la',  emoji:'💵'},
    ]},
  { id:'O',   label:'O',   ipa:'oʊ', type:'vowel', group:'Single Vowels',
    color:'bg-red-600',     grad:'from-red-600 to-red-800',        hard:false,
    tip:'Bắt đầu "o" rồi trượt sang "u" nhẹ — diphthong ngắn. Không phải "ô" đơn',
    words:[
      {word:'go',   meaning:'đi',        emoji:'🏃'},
      {word:'home', meaning:'nhà',       emoji:'🏠'},
      {word:'road', meaning:'con đường', emoji:'🛣️'},
      {word:'cold', meaning:'lạnh',      emoji:'🥶'},
    ]},
  { id:'E',   label:'E',   ipa:'iː', type:'vowel', group:'Single Vowels',
    color:'bg-emerald-600', grad:'from-emerald-600 to-emerald-800',hard:false,
    tip:'Âm /i/ trong các từ kết thúc bằng -y, -ey, -ie — nhẹ và ngắn hơn EE',
    words:[
      {word:'happy',  meaning:'vui vẻ',    emoji:'😊'},
      {word:'city',   meaning:'thành phố', emoji:'🏙️'},
      {word:'very',   meaning:'rất',       emoji:'💪'},
      {word:'funny',  meaning:'buồn cười', emoji:'😄'},
    ]},
  { id:'A',   label:'A',   ipa:'eɪ', type:'vowel', group:'Single Vowels',
    color:'bg-blue-600',    grad:'from-blue-600 to-blue-800',      hard:false,
    tip:'Tên chữ cái A — bắt đầu "e" trượt lên "i". Giống EY nhưng trong pattern chữ a-e',
    words:[
      {word:'name',  meaning:'tên',           emoji:'🏷️'},
      {word:'face',  meaning:'khuôn mặt',     emoji:'😊'},
      {word:'say',   meaning:'nói',           emoji:'💬'},
      {word:'place', meaning:'địa điểm',      emoji:'📍'},
    ]},

  // ════════════════════════════════════════════════════════════
  // VOWELS — Vowel Combinations (Diphthongs) · 9 sounds
  // ════════════════════════════════════════════════════════════
  { id:'EY',  label:'EY',  ipa:'eɪ', type:'vowel', group:'Diphthongs',
    color:'bg-violet-600',  grad:'from-violet-600 to-violet-800',  hard:false,
    tip:'Bắt đầu "e" rồi trượt lên "i" — như trong "say, day"',
    words:[
      {word:'say',    meaning:'nói',        emoji:'💬'},
      {word:'great',  meaning:'tuyệt vời',  emoji:'🌟'},
      {word:'make',   meaning:'làm',        emoji:'🔨'},
      {word:'table',  meaning:'cái bàn',    emoji:'🪑'},
    ]},
  { id:'ai',  label:'ai',  ipa:'aɪ', type:'vowel', group:'Diphthongs',
    color:'bg-teal-600',    grad:'from-teal-600 to-teal-800',      hard:false,
    tip:'Từ "a" rộng trượt lên "i" — như "night, like". Không phải "ây" đơn',
    words:[
      {word:'nice',  meaning:'tốt, dễ chịu',emoji:'😊'},
      {word:'bike',  meaning:'xe đạp',     emoji:'🚲'},
      {word:'night', meaning:'đêm',        emoji:'🌙'},
      {word:'right', meaning:'đúng',       emoji:'✅'},
    ]},
  { id:'OY',  label:'OY',  ipa:'ɔɪ', type:'vowel', group:'Diphthongs',
    color:'bg-indigo-600',  grad:'from-indigo-600 to-indigo-800',  hard:false,
    tip:'Từ "ô" tròn trượt lên "i" — như "boy, oil". Giống âm "oi" tiếng Việt',
    words:[
      {word:'boy',    meaning:'con trai',   emoji:'👦'},
      {word:'oil',    meaning:'dầu',        emoji:'🛢️'},
      {word:'voice',  meaning:'giọng nói',  emoji:'🎤'},
      {word:'enjoy',  meaning:'tận hưởng',  emoji:'😄'},
    ]},
  { id:'OH',  label:'OH',  ipa:'oʊ', type:'vowel', group:'Diphthongs',
    color:'bg-pink-600',    grad:'from-pink-600 to-pink-800',      hard:false,
    tip:'Từ "o" trượt sang "u" nhẹ. Đây là "long O" trong tiếng Anh',
    words:[
      {word:'old',   meaning:'già, cũ',  emoji:'👴'},
      {word:'notes', meaning:'ghi chú',  emoji:'📒'},
      {word:'phone', meaning:'điện thoại',emoji:'📱'},
      {word:'open',  meaning:'mở',       emoji:'🚪'},
    ]},
  { id:'OW',  label:'OW',  ipa:'aʊ', type:'vowel', group:'Diphthongs',
    color:'bg-cyan-600',    grad:'from-cyan-600 to-cyan-800',      hard:false,
    tip:'Từ "a" rộng trượt lên "u" — như "now, out". Không phải "ao" tiếng Việt',
    words:[
      {word:'loud',   meaning:'to, ồn ào', emoji:'📢'},
      {word:'now',    meaning:'bây giờ',   emoji:'⏰'},
      {word:'house',  meaning:'ngôi nhà',  emoji:'🏠'},
      {word:'south',  meaning:'phía nam',  emoji:'🧭'},
    ]},
  { id:'AR',  label:'AR',  ipa:'ɑːr',type:'vowel', group:'Diphthongs',
    color:'bg-teal-700',    grad:'from-teal-700 to-teal-900',      hard:false,
    tip:'Âm "a" dài + cuộn lưỡi nhẹ ra sau (giọng Mỹ). Như "car, large"',
    words:[
      {word:'car',   meaning:'xe hơi',  emoji:'🚗'},
      {word:'large', meaning:'to lớn',  emoji:'🐘'},
      {word:'start', meaning:'bắt đầu', emoji:'▶️'},
      {word:'heart', meaning:'trái tim',emoji:'❤️'},
    ]},
  { id:'OR',  label:'OR',  ipa:'ɔːr',type:'vowel', group:'Diphthongs',
    color:'bg-amber-700',   grad:'from-amber-700 to-amber-900',    hard:false,
    tip:'Âm "ô" tròn + cuộn lưỡi. Như "more, door, for"',
    words:[
      {word:'more',  meaning:'thêm',    emoji:'➕'},
      {word:'door',  meaning:'cánh cửa',emoji:'🚪'},
      {word:'story', meaning:'câu chuyện',emoji:'📖'},
      {word:'before',meaning:'trước',   emoji:'⏮️'},
    ]},
  { id:'AIR', label:'AIR', ipa:'ɛər',type:'vowel', group:'Diphthongs',
    color:'bg-orange-600',  grad:'from-orange-600 to-orange-800',  hard:false,
    tip:'Âm "e" + schwa + cuộn lưỡi. Như "where, chair, square"',
    words:[
      {word:'chair',  meaning:'cái ghế',  emoji:'🪑'},
      {word:'where',  meaning:'ở đâu',    emoji:'📍'},
      {word:'there',  meaning:'ở đó',     emoji:'👉'},
      {word:'careful',meaning:'cẩn thận', emoji:'⚠️'},
    ]},
  { id:'EAR', label:'EAR', ipa:'ɪər',type:'vowel', group:'Diphthongs',
    color:'bg-red-500',     grad:'from-red-500 to-red-700',        hard:false,
    tip:'Âm "i" ngắn + schwa + cuộn lưỡi. Như "near, here, hear"',
    words:[
      {word:'near',  meaning:'gần',       emoji:'📏'},
      {word:'here',  meaning:'ở đây',     emoji:'🏠'},
      {word:'hear',  meaning:'nghe',      emoji:'👂'},
      {word:'really',meaning:'thực sự',   emoji:'💯'},
    ]},

  // ════════════════════════════════════════════════════════════
  // CONSONANTS — Plosives · 6 sounds
  // ════════════════════════════════════════════════════════════
  { id:'P',   label:'P',   ipa:'p',  type:'consonant', group:'Plosives',
    color:'bg-fuchsia-600', grad:'from-fuchsia-600 to-fuchsia-800',hard:false,
    tip:'Khép môi hoàn toàn, tích tụ khí rồi bật ra mạnh (aspirated khi đầu từ)',
    words:[
      {word:'pretty', meaning:'xinh đẹp',emoji:'🌸'},
      {word:'plant',  meaning:'cây',     emoji:'🌿'},
      {word:'people', meaning:'người',   emoji:'👥'},
      {word:'stop',   meaning:'dừng',    emoji:'🛑'},
    ]},
  { id:'B',   label:'B',   ipa:'b',  type:'consonant', group:'Plosives',
    color:'bg-blue-600',    grad:'from-blue-600 to-blue-800',      hard:false,
    tip:'Giống P nhưng RUNG HỌng. Bật môi + rung dây thanh âm',
    words:[
      {word:'baby',  meaning:'em bé',    emoji:'👶'},
      {word:'bird',  meaning:'con chim', emoji:'🐦'},
      {word:'book',  meaning:'cuốn sách',emoji:'📖'},
      {word:'big',   meaning:'to lớn',   emoji:'🐘'},
    ]},
  { id:'T',   label:'T',   ipa:'t',  type:'consonant', group:'Plosives',
    color:'bg-emerald-600', grad:'from-emerald-600 to-emerald-800',hard:false,
    tip:'Lưỡi chạm sau răng cửa trên, bật ra. Đầu từ có hơi thở (aspirated)',
    words:[
      {word:'tiny',   meaning:'tí hon',  emoji:'🐜'},
      {word:'turtle', meaning:'rùa',     emoji:'🐢'},
      {word:'table',  meaning:'cái bàn', emoji:'🪑'},
      {word:'time',   meaning:'thời gian',emoji:'⏰'},
    ]},
  { id:'D',   label:'D',   ipa:'d',  type:'consonant', group:'Plosives',
    color:'bg-amber-600',   grad:'from-amber-600 to-amber-800',    hard:false,
    tip:'Giống T nhưng RUNG HỌng. Lưỡi chạm sau răng + rung dây thanh âm',
    words:[
      {word:'dinner', meaning:'bữa tối', emoji:'🍽️'},
      {word:'date',   meaning:'ngày tháng',emoji:'📅'},
      {word:'dog',    meaning:'con chó', emoji:'🐶'},
      {word:'deep',   meaning:'sâu',     emoji:'🌊'},
    ]},
  { id:'K',   label:'K',   ipa:'k',  type:'consonant', group:'Plosives',
    color:'bg-orange-600',  grad:'from-orange-600 to-orange-800',  hard:false,
    tip:'Lưỡi chạm vòm mềm PHÍA SAU miệng, bật ra. Đầu từ có hơi thở',
    words:[
      {word:'candy', meaning:'kẹo',     emoji:'🍬'},
      {word:'cane',  meaning:'gậy',     emoji:'🦯'},
      {word:'kind',  meaning:'tốt bụng',emoji:'💛'},
      {word:'clock', meaning:'đồng hồ', emoji:'🕐'},
    ]},
  { id:'G',   label:'G',   ipa:'g',  type:'consonant', group:'Plosives',
    color:'bg-red-600',     grad:'from-red-600 to-red-800',        hard:false,
    tip:'Giống K nhưng RUNG HỌng. Lưỡi vòm mềm + rung dây thanh âm',
    words:[
      {word:'giggly', meaning:'hay cười',emoji:'😄'},
      {word:'girl',   meaning:'con gái', emoji:'👧'},
      {word:'good',   meaning:'tốt',     emoji:'👍'},
      {word:'big',    meaning:'to lớn',  emoji:'🐘'},
    ]},

  // ════════════════════════════════════════════════════════════
  // CONSONANTS — Nasals · 3 sounds
  // ════════════════════════════════════════════════════════════
  { id:'M',   label:'M',   ipa:'m',  type:'consonant', group:'Nasals',
    color:'bg-purple-600',  grad:'from-purple-600 to-purple-800',  hard:false,
    tip:'Khép môi hoàn toàn, cho khí thoát qua MŨI. Rung cả mũi khi phát âm',
    words:[
      {word:'meek',  meaning:'hiền lành', emoji:'🕊️'},
      {word:'mouse', meaning:'con chuột', emoji:'🐭'},
      {word:'moon',  meaning:'mặt trăng', emoji:'🌙'},
      {word:'name',  meaning:'tên',       emoji:'🏷️'},
    ]},
  { id:'N',   label:'N',   ipa:'n',  type:'consonant', group:'Nasals',
    color:'bg-red-800',     grad:'from-red-800 to-red-900',        hard:false,
    tip:'Lưỡi chạm sau răng cửa trên, khí thoát qua MŨI. Không bật lưỡi',
    words:[
      {word:'new',      meaning:'mới',      emoji:'✨'},
      {word:'necklace', meaning:'vòng cổ',  emoji:'📿'},
      {word:'name',     meaning:'tên',      emoji:'🏷️'},
      {word:'night',    meaning:'đêm',      emoji:'🌙'},
    ]},
  { id:'NG',  label:'NG',  ipa:'ŋ',  type:'consonant', group:'Nasals',
    color:'bg-rose-700',    grad:'from-rose-700 to-rose-900',      hard:false,
    tip:'Lưỡi chạm vòm MỀM phía sau, khí qua mũi. Không có âm "g" riêng lẻ sau /ŋ/',
    words:[
      {word:'ring',     meaning:'chiếc nhẫn',emoji:'💍'},
      {word:'song',     meaning:'bài hát',  emoji:'🎵'},
      {word:'morning',  meaning:'buổi sáng',emoji:'🌅'},
      {word:'learning', meaning:'học hỏi',  emoji:'📚'},
    ]},

  // ════════════════════════════════════════════════════════════
  // CONSONANTS — Fricatives · 9 sounds
  // ════════════════════════════════════════════════════════════
  { id:'F',   label:'F',   ipa:'f',  type:'consonant', group:'Fricatives',
    color:'bg-green-600',   grad:'from-green-600 to-green-800',    hard:false,
    tip:'Răng cửa TRÊN đặt lên môi DƯỚI, thổi khí nhẹ. KHÔNG rung họng',
    words:[
      {word:'furry',  meaning:'có lông xù',emoji:'🐻'},
      {word:'friend', meaning:'bạn bè',    emoji:'🤝'},
      {word:'food',   meaning:'thức ăn',   emoji:'🍜'},
      {word:'phone',  meaning:'điện thoại',emoji:'📱'},
    ]},
  { id:'V',   label:'V',   ipa:'v',  type:'consonant', group:'Fricatives',
    color:'bg-blue-600',    grad:'from-blue-600 to-blue-800',      hard:true,
    tip:'Giống F nhưng RUNG HỌng. Răng trên + môi dưới + rung dây thanh. KHÔNG phải "b"!',
    words:[
      {word:'vital',     meaning:'quan trọng',emoji:'⭐'},
      {word:'vegetable', meaning:'rau củ',   emoji:'🥦'},
      {word:'voice',     meaning:'giọng nói',emoji:'🎤'},
      {word:'very',      meaning:'rất',      emoji:'💪'},
    ]},
  { id:'th',  label:'th',  ipa:'θ',  type:'consonant', group:'Fricatives',
    color:'bg-violet-600',  grad:'from-violet-600 to-violet-800',  hard:true,
    tip:'ĐẶT ĐẦU LƯỠI GIỮA HAI HÀNG RĂNG, thổi khí nhẹ KHÔNG rung họng. Khó nhất!',
    words:[
      {word:'think',    meaning:'suy nghĩ',  emoji:'💭'},
      {word:'three',    meaning:'ba',        emoji:'3️⃣'},
      {word:'bath',     meaning:'tắm',       emoji:'🛁'},
      {word:'earth',    meaning:'trái đất',  emoji:'🌍'},
    ]},
  { id:'TH',  label:'TH',  ipa:'ð',  type:'consonant', group:'Fricatives',
    color:'bg-teal-700',    grad:'from-teal-700 to-teal-900',      hard:true,
    tip:'Giống th nhưng RUNG HỌng. Lưỡi giữa răng + rung dây thanh âm',
    words:[
      {word:'this',    meaning:'cái này',  emoji:'👆'},
      {word:'mother',  meaning:'mẹ',       emoji:'👩'},
      {word:'weather', meaning:'thời tiết',emoji:'⛅'},
      {word:'breathe', meaning:'thở',      emoji:'🫁'},
    ]},
  { id:'S',   label:'S',   ipa:'s',  type:'consonant', group:'Fricatives',
    color:'bg-pink-600',    grad:'from-pink-600 to-pink-800',      hard:false,
    tip:'Đầu lưỡi gần (không chạm) sau răng cửa trên, thổi khí. Không rung họng',
    words:[
      {word:'soft',    meaning:'mềm',      emoji:'🧸'},
      {word:'sweater', meaning:'áo len',   emoji:'🧥'},
      {word:'school',  meaning:'trường',   emoji:'🏫'},
      {word:'sleep',   meaning:'ngủ',      emoji:'😴'},
    ]},
  { id:'Z',   label:'Z',   ipa:'z',  type:'consonant', group:'Fricatives',
    color:'bg-slate-600',   grad:'from-slate-600 to-slate-800',    hard:false,
    tip:'Giống S nhưng RUNG HỌng. Hay xuất hiện ở cuối từ số nhiều (-s) và động từ',
    words:[
      {word:'lazy',  meaning:'lười biếng',emoji:'😴'},
      {word:'zebra', meaning:'ngựa vằn', emoji:'🦓'},
      {word:'music', meaning:'âm nhạc',  emoji:'🎵'},
      {word:'nose',  meaning:'cái mũi',  emoji:'👃'},
    ]},
  { id:'SH',  label:'SH',  ipa:'ʃ',  type:'consonant', group:'Fricatives',
    color:'bg-fuchsia-700', grad:'from-fuchsia-700 to-fuchsia-900',hard:false,
    tip:'Chu môi nhẹ ra phía trước, thổi khí. Không rung họng. Như "ssh" khi bảo im lặng',
    words:[
      {word:'shiny', meaning:'sáng bóng',emoji:'✨'},
      {word:'shoes', meaning:'đôi giày', emoji:'👟'},
      {word:'she',   meaning:'cô ấy',   emoji:'👩'},
      {word:'wish',  meaning:'mong muốn',emoji:'⭐'},
    ]},
  { id:'ZH',  label:'ZH',  ipa:'ʒ',  type:'consonant', group:'Fricatives',
    color:'bg-red-800',     grad:'from-red-800 to-red-950',        hard:true,
    tip:'Giống SH nhưng RUNG HỌng. Ít gặp — chỉ trong "measure, treasure, vision"',
    words:[
      {word:'measure',  meaning:'đo lường',emoji:'📏'},
      {word:'treasure', meaning:'kho báu', emoji:'💎'},
      {word:'usual',    meaning:'thông thường',emoji:'📋'},
      {word:'vision',   meaning:'tầm nhìn',emoji:'👁️'},
    ]},
  { id:'H',   label:'H',   ipa:'h',  type:'consonant', group:'Fricatives',
    color:'bg-rose-600',    grad:'from-rose-600 to-rose-800',      hard:false,
    tip:'Thổi khí nhẹ từ họng, như hơi thở nhẹ. Không rung họng. Đơn giản nhất!',
    words:[
      {word:'happy', meaning:'vui vẻ',    emoji:'😊'},
      {word:'hippo', meaning:'hà mã',     emoji:'🦛'},
      {word:'home',  meaning:'nhà',       emoji:'🏠'},
      {word:'hand',  meaning:'bàn tay',   emoji:'✋'},
    ]},

  // ════════════════════════════════════════════════════════════
  // CONSONANTS — Approximants · 4 sounds
  // ════════════════════════════════════════════════════════════
  { id:'R',   label:'R',   ipa:'r',  type:'consonant', group:'Approximants',
    color:'bg-teal-600',    grad:'from-teal-600 to-teal-800',      hard:true,
    tip:'KHÔNG CHẠM LƯỠI VÀO ĐÂU — cuộn lưỡi ra sau giữa không khí, môi hơi thu tròn. Khác /l/ hoàn toàn!',
    words:[
      {word:'prickly',meaning:'gai góc',  emoji:'🌵'},
      {word:'branch', meaning:'cành cây', emoji:'🌿'},
      {word:'road',   meaning:'con đường',emoji:'🛣️'},
      {word:'really', meaning:'thực sự',  emoji:'💯'},
    ]},
  { id:'Y',   label:'Y',   ipa:'j',  type:'consonant', group:'Approximants',
    color:'bg-pink-500',    grad:'from-pink-500 to-pink-700',      hard:false,
    tip:'Lưỡi cao phía trước, miệng hé — giống "i" tiếng Việt nhưng chuyển sang nguyên âm ngay',
    words:[
      {word:'yummy',  meaning:'ngon',     emoji:'😋'},
      {word:'yogurt', meaning:'sữa chua', emoji:'🥛'},
      {word:'year',   meaning:'năm',      emoji:'📅'},
      {word:'you',    meaning:'bạn',      emoji:'👤'},
    ]},
  { id:'W',   label:'W',   ipa:'w',  type:'consonant', group:'Approximants',
    color:'bg-sky-600',     grad:'from-sky-600 to-sky-800',        hard:true,
    tip:'Chu môi tròn như chuẩn bị nói "oa", KHÔNG dùng răng. Khác /v/ hoàn toàn!',
    words:[
      {word:'wonderful',meaning:'tuyệt vời',emoji:'🌟'},
      {word:'whale',    meaning:'cá voi',  emoji:'🐋'},
      {word:'water',    meaning:'nước',    emoji:'💧'},
      {word:'world',    meaning:'thế giới',emoji:'🌍'},
    ]},
  { id:'L',   label:'L',   ipa:'l',  type:'consonant', group:'Approximants',
    color:'bg-purple-600',  grad:'from-purple-600 to-purple-800',  hard:false,
    tip:'ĐẦU LƯỠI CHẠM sau răng cửa trên. Khác /r/: lưỡi chạm một điểm cố định',
    words:[
      {word:'lemon',    meaning:'chanh',     emoji:'🍋'},
      {word:'lollipop', meaning:'kẹo mút',   emoji:'🍭'},
      {word:'light',    meaning:'ánh sáng',  emoji:'💡'},
      {word:'world',    meaning:'thế giới',  emoji:'🌍'},
    ]},

  // ════════════════════════════════════════════════════════════
  // CONSONANTS — Affricates · 2 sounds
  // ════════════════════════════════════════════════════════════
  { id:'CH',  label:'CH',  ipa:'tʃ', type:'consonant', group:'Affricates',
    color:'bg-amber-600',   grad:'from-amber-600 to-amber-800',    hard:false,
    tip:'Kết hợp /t/ + /ʃ/ liền nhau. Lưỡi chạm vòm miệng rồi bật ra với luồng khí',
    words:[
      {word:'cheddar', meaning:'phô mai',  emoji:'🧀'},
      {word:'cheese',  meaning:'phô mai',  emoji:'🧀'},
      {word:'church',  meaning:'nhà thờ',  emoji:'⛪'},
      {word:'teacher', meaning:'giáo viên',emoji:'👩‍🏫'},
    ]},
  { id:'J',   label:'J',   ipa:'dʒ', type:'consonant', group:'Affricates',
    color:'bg-orange-500',  grad:'from-orange-500 to-orange-700',  hard:false,
    tip:'Giống CH nhưng RUNG HỌng. Kết hợp /d/ + /ʒ/. Như "judge, just, magic"',
    words:[
      {word:'gentle', meaning:'nhẹ nhàng',emoji:'🕊️'},
      {word:'giant',  meaning:'khổng lồ', emoji:'🦕'},
      {word:'just',   meaning:'vừa, chỉ', emoji:'🎯'},
      {word:'enjoy',  meaning:'tận hưởng',emoji:'😄'},
    ]},

  // ════════════════════════════════════════════════════════════
  // CONSONANTS — Tap · 1 sound
  // ════════════════════════════════════════════════════════════
  { id:'DD',  label:'DD',  ipa:'ɾ',  type:'consonant', group:'Tap',
    color:'bg-violet-700',  grad:'from-violet-700 to-violet-900',  hard:true,
    tip:'Flap T — âm đặc trưng giọng Mỹ: /t/ và /d/ giữa hai nguyên âm phát âm như "d" nhanh. "butter" = "budder"',
    words:[
      {word:'muddy',  meaning:'bùn lầy',  emoji:'🌧️'},
      {word:'city',   meaning:'thành phố',emoji:'🏙️'},
      {word:'water',  meaning:'nước',     emoji:'💧'},
      {word:'better', meaning:'tốt hơn',  emoji:'⬆️'},
    ]},
]

// Grouped for the Sound Library UI
export const VOWEL_GROUPS = [
  { label: 'Single Vowels', key: 'Single Vowels', count: 14 },
  { label: 'Diphthongs',    key: 'Diphthongs',    count: 9  },
]
export const CONSONANT_GROUPS = [
  { label: 'Plosives',      key: 'Plosives',      count: 6 },
  { label: 'Nasals',        key: 'Nasals',         count: 3 },
  { label: 'Fricatives',    key: 'Fricatives',     count: 9 },
  { label: 'Approximants',  key: 'Approximants',   count: 4 },
  { label: 'Affricates',    key: 'Affricates',     count: 2 },
  { label: 'Tap',           key: 'Tap',            count: 1 },
]
